config/routes.rb
Rails.application.routes.draw do
  resources :invoice_bags
  resources :invoices
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invoice.rb
class Invoice < ApplicationRecord

  has_many :invoice_invoice_bags, dependent: :destroy
  has_many :invoice_bags, through: :invoice_invoice_bags

  after_commit: update_invoices

  private

  def update_invoices
    InvoiceReSyncJob.perform_async(self)
  end
end

app/models/invoice_bag.rb
class InvoiceBag < ApplicationRecord
  has_many :invoice_invoice_bags, dependent: :destroy
  has_many :invoices, through: :invoice_invoice_bags
end

app/models/invoice_invoice_bag.rb
class InvoiceInvoiceBag < ApplicationRecord
  belongs_to :invoice
  belongs_to :invoice_bag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/invoice_bags_controller.rb
class InvoiceBagsController < ApplicationController
  before_action :set_invoice_bag, only: %i[ show edit update destroy ]

  # GET /invoice_bags or /invoice_bags.json
  def index
    @invoice_bags = InvoiceBag.all
  end

  # GET /invoice_bags/1 or /invoice_bags/1.json
  def show
  end

  # GET /invoice_bags/new
  def new
    @invoice_bag = InvoiceBag.new
  end

  # GET /invoice_bags/1/edit
  def edit
  end

  # POST /invoice_bags or /invoice_bags.json
  def create
    @invoice_bag = InvoiceBag.new(invoice_bag_params)

    respond_to do |format|
      if @invoice_bag.save
        format.html { redirect_to invoice_bag_url(@invoice_bag), notice: "Invoice bag was successfully created." }
        format.json { render :show, status: :created, location: @invoice_bag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice_bag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_bags/1 or /invoice_bags/1.json
  def update
    respond_to do |format|
      if @invoice_bag.update(invoice_bag_params)
        format.html { redirect_to invoice_bag_url(@invoice_bag), notice: "Invoice bag was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice_bag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice_bag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_bags/1 or /invoice_bags/1.json
  def destroy
    @invoice_bag.destroy

    respond_to do |format|
      format.html { redirect_to invoice_bags_url, notice: "Invoice bag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_bag
      @invoice_bag = InvoiceBag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_bag_params
      params.require(:invoice_bag).permit(:total_amount, :name)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: %i[ show edit update destroy ]

  # GET /invoices or /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1 or /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices or /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully created." }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1 or /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to invoice_url(@invoice), notice: "Invoice was successfully updated." }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1 or /invoices/1.json
  def destroy
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to invoices_url, notice: "Invoice was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_params
      params.require(:invoice).permit(:amount, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoice_bags_helper.rb
module InvoiceBagsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoice_bags/_form.html.erb
<%= form_with(model: invoice_bag) do |form| %>
  <% if invoice_bag.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invoice_bag.errors.count, "error") %> prohibited this invoice_bag from being saved:</h2>

      <ul>
        <% invoice_bag.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :total_amount, style: "display: block" %>
    <%= form.number_field :total_amount %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_bags/_invoice_bag.html.erb
<div id="<%= dom_id invoice_bag %>">
  <p>
    <strong>Total amount:</strong>
    <%= invoice_bag.total_amount %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= invoice_bag.name %>
  </p>

</div>

app/views/invoice_bags/edit.html.erb
<h1>Editing invoice bag</h1>

<%= render "form", invoice_bag: @invoice_bag %>

<br>

<div>
  <%= link_to "Show this invoice bag", @invoice_bag %> |
  <%= link_to "Back to invoice bags", invoice_bags_path %>
</div>

app/views/invoice_bags/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Invoice bags</h1>

<div id="invoice_bags">
  <% @invoice_bags.each do |invoice_bag| %>
    <%= render invoice_bag %>
    <p>
      <%= link_to "Show this invoice bag", invoice_bag %>
    </p>
  <% end %>
</div>

<%= link_to "New invoice bag", new_invoice_bag_path %>

app/views/invoice_bags/new.html.erb
<h1>New invoice bag</h1>

<%= render "form", invoice_bag: @invoice_bag %>

<br>

<div>
  <%= link_to "Back to invoice bags", invoice_bags_path %>
</div>

app/views/invoice_bags/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @invoice_bag %>

<div>
  <%= link_to "Edit this invoice bag", edit_invoice_bag_path(@invoice_bag) %> |
  <%= link_to "Back to invoice bags", invoice_bags_path %>

  <%= button_to "Destroy this invoice bag", @invoice_bag, method: :delete %>
</div>

app/views/invoices/_form.html.erb
<%= form_with(model: invoice) do |form| %>
  <% if invoice.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
        <% invoice.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.number_field :amount %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/invoices/_invoice.html.erb
<div id="<%= dom_id invoice %>">
  <p>
    <strong>Amount:</strong>
    <%= invoice.amount %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= invoice.name %>
  </p>

</div>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Show this invoice", @invoice %> |
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Invoices</h1>

<div id="invoices">
  <% @invoices.each do |invoice| %>
    <%= render invoice %>
    <p>
      <%= link_to "Show this invoice", invoice %>
    </p>
  <% end %>
</div>

<%= link_to "New invoice", new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render "form", invoice: @invoice %>

<br>

<div>
  <%= link_to "Back to invoices", invoices_path %>
</div>

app/views/invoices/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @invoice %>

<div>
  <%= link_to "Edit this invoice", edit_invoice_path(@invoice) %> |
  <%= link_to "Back to invoices", invoices_path %>

  <%= button_to "Destroy this invoice", @invoice, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvoiceBatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>